version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.Build.Framework
    versions:
    - 16.8.0
  - dependency-name: Microsoft.Build
    versions:
    - 16.8.0
  - dependency-name: Microsoft.Build.Tasks.Core
    versions:
    - 16.8.0
  - dependency-name: Microsoft.Build.Utilities.Core
    versions:
    - 16.8.0
